Create auth
DeskproApps/youtrack pull request #2
Opened 2023-01-20 08:36 UTC by zpawn

Story https://app.shortcut.com/deskpro/story/98878/youtrack-auth

2023-01-20 12:27 UTC, iTweeno requested changes
We need to write tests to see if this works.

2023-01-20 13:46 UTC, zpawn commented
> We need to write tests to see if this works.

hey @iTweeno it's work, trust me )))

2023-01-20 13:47 UTC, zpawn commented
> We need to write tests to see if this works.

hey @iTweeno it's work, trust me)))

I think that it's necessary to make an MVP as soon as possible, and then write tests

2023-01-20 13:50 UTC, iTweeno commented
I trust it works, but this is part of the new quality process in Apps, where we need,

1. Evidence of Acceptance Criteria
2. Tests written for major functions of the feature (with suitable vendor API mocks)

2023-01-23 09:33 UTC, iTweeno requested changes

2023-01-23 09:33 UTC, iTweeno commented on src/pages/VerifySettings/__tests__/VerifySettings.test.tsx
> +      expect(text).toBeInTheDocument();
Alright so, In this test you're only seeing if verify Settings is inside the page, not actually seeing if the implementation works fine. Some API mocks would be required in order to see if this implementation works.

2023-01-23 09:41 UTC, iTweeno approved these changes

2023-01-25 15:47 UTC, merged